controller_list:
  - name: fake_jaka_s5_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_dh_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - ag145_gripper_finger1_joint
initial:  # Define initial robot poses per group
  - group: jaka_s5
    pose: zero
  - group: dh_gripper
    pose: close